server:
  port: 8082

spring:
  application:
    name: consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    #需要增加下面配置，告诉注册中心访问路径变化
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /