server:
  port: 9082
spring:
  application:
    name: user-server
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30  #心跳续约
    lease-expiration-duration-in-seconds: 90 #服务失效时间